### PR TITLE
House

### PR DESCRIPTION
**Pull request by annaoliinyk**
Instructions
Recite the nursery rhyme 'This is the House that Jack Built'.

Task source: https://exercism.org/tracks/python/exercises/house

### CODE REVIEW

**Review by AnaKovaGH — CHANGES_REQUESTED** [review]
The main purpose of the task is to "walk" through the text with adding new line every cycle. Not just hard-coding each line.
Please re-write.

**Comment by annaoliinyk** [comment]
This was fixed

**Review by AnaKovaGH — CHANGES_REQUESTED** [review]
Please remove hard-coding from the code and just add new words as it written

**Comment by annaoliinyk** [comment]
Fixed

**Review by AnaKovaGH — APPROVED** [review]

**Pull request merged**
